* 26 juin 2019
- Public: 40 profs de collège/lycée en maths/SI, quelques profs du supérieur
- Animateur Martin, avec l'aide d'un collègue qui a fait sa thèse en TAL
- Durée: une grosse demi-heure
- Déroulé
  - Imaginez que vous travaillez pour un site présentant sur internet les films.
    Vous demandez aux participants de donner leur avis sur les films, et ils
    écrivent des textes assez courts. On voudrait pouvoir classer les
    commentaires entre ceux qui disent du bien et ceux du mal des films, afin de
    les présenter aux futurs visiteurs.
  - Distribution du jeu de cartes 1, avec comme seule consigne de faire le tri.
    Ils sont employés du site pour faire la dite classification.
  - On laisse le groupe trier un gros quart d'heure, 20mn.
    - TODO: on manque d'extension pour ceux qui vont vite
    - Certains participants qui discutaillent beaucoup la classification. 
      Ils peuvent faire une pile "je sais pas trop".
  - Ensuite, on reprend la main en groupe entier pour annoncer que maintenant,
    on voudrait externaliser la classification en Inde.
    - Les participants doivent donc s'interroger sur comment ils ont classifié
    - Comment permettre à quelqu'un n'ayant pas accès au sens du texte de classifier ?
    - L'idée d'étiqueter les mots ou les expressions vient assez naturellement.
  - Regroupement pour réfléchir à une stratégie, qui arrive dont à l'étiquetage.
    - TODO: pour la conclusion de ce regroupement, ce serait bien d'avoir un
      support à la place du jeu de cartes 2 où toutes les phrases sont notés
      (ordre alphabétique?) avec cette stratégie appliquée. Si ça tient en un
      recto/verso, on peut en imprimer un par groupe, ce qui permet même de
      l'écrire petit (11pt), et donc de pouvoir en écrire plus sur la page.
  - Une fois la stratégie explicité, on peut tenter de la faire tourner sur un
    autre corpus (qu'il faudrait créer)

  - En ouverture, on va parler des limites de l'approche
    - *Problème 1*: comment on étiquette ?
      - Avant, on demandait aux doctorants de produire des corpus classifiés
        pour nourrir les algos.
      - Maintenant, big data.
        - On demande aux gens de classifier (mettre une évaluation de 1 à 5
          étoiles avec le commentaire, et on utilise l'algo pour vérifier qu'ils
          pipotent pas).
        - C'est d'ailleurs ce que google fait sur les captchas. En fait, ils
          nous donnent 5 images sur lesquelles ils connaissent la réponse et une
          ou deux images où ils savent pas. Certaines servent à vérifier qu'on
          ne répond pas au hasard, et les autres leur permettent de classifier
          pour les prochains.
    - *Problème 2*: limites de cette méthode d'étiquettage des mots du corpus?
      - On distribue la 3ieme pile de cartes, et on réfléchi ensemble aux problèmes posés.
      - TODO: il faudrait une fiche de l'animateur sur ces aspects.
