# Il faudrait tout regénérer et mettre les liens depuis le document, comme on fait pour les rapports d'étonnement
#MATOS=Materiel/2025_Meneux_Wojtecki.pdf
#PREPS=FicheDePreparation/2025_Meneux_Wojtecki.pdf
#TRACES=Traces/2025_Meneux_Wojtecki.pdf


include ../Makefile.defs
