* 26 juin 2019
- Public: 40 profs de collège/lycée en maths/SI, quelques profs du supérieur
- Animateur Martin
- Durée: 45mn
- Déroulé: J'ai fait très classique, et ça s'est bien passé.
  - "voici une activité portant sur les langages", puis introduction de
    l'activité de figure téléphonée, puis on les laisse maniper.
  - J'ai interrompu au bout d'un temps car de toute façon il y avait trop de
    matheux pour que ce soit marrant avec la fiche A. Ces gens savent s'expriemr
    avec rigueur sans ambiguité en cas de besoin.
  - J'ai donc fait la fiche "mettons nous d'accord" en décrivant ce qui se passe
    habituellement: les disputes entre participants "ils comprenent rien" vs.
    "mais il dit n'importe quoi", puis j'ai distribué la fiche de voca avant de
    relancer sur la fiche B.
  - J'ai distribué la fiche C sur les tables au bout d'un temps, discretement.
    Toutes les tables ne l'ont pas utilisé et c'est pas grave. C'est une
    extension tfacon.
  - Puis conclusion en regroupement, qui s'est très bien passé.
  - Plusieurs de collègues ont photocopié le matériel pour se l'approprier
- C'est de l'informatique
  - un programme est une verbalisation non ambigue d'un algorithme utilisant un
    vocabulaire prédéfini
  - Encodage d'image au format vectoriel, avec lien à l'activité image binaire
    de CS unplug
  - Complexité de l'information, avec la question de savoir comment on a rangé
    les figures en 3 fiches de plus en plus dures (en les triant par longueur de
    description).
  - Récursivité possible: On pourrait probablement en faire une activité
    branchée riche sur la découverte de la récursivité à la suite de celle-ci.
    Mais faudrait le faire :)
